import { Console } from 'console';
import { useState, useEffect } from 'react';

// Objeto con las traducciones
const translations = {
  en: {
    "statusUpdated": "Status updated successfully",
    "settings": "Settings",
    "security": "Security",
    "fullName": "Full Name",
    "email": "Email",
    "emailCannotBeChanged": "Email cannot be changed",
    "confirmDeleteTicket": "Delete ticket",
    "deleteTicketWarning": "Are you sure you want to delete this ticket? This action cannot be undone.",
    "createSuggestionNow": "Create new suggestion",
    "titleIncident": "Incident Title",
    "descrpitionIncident": "Description of the incident",
    "title": "Title:",
    "attachImages": "Attach images",
    "uploadImagesDesc": "Upload images related to your issue. You can attach multiple images.",
    "clickToUpload": "Click to upload images",
    "navigation": "Navigation",
    "dashboard": "Dashboard",
    "tickets": "Tickets",
    "newTicket": "New ticket",
    "search": "Search",
    "profile": "Profile",
    "suggestions": "Suggestions",    "adminSuggestions": "Manage suggestions",
    "adminAssignedTickets": "My assigned tickets",
    "assignedTickets": "My assigned tickets",
    "noAssignedTickets": "No assigned tickets",
    "noAssignedTicketsDesc": "You don't have any tickets assigned to you yet",
    "allTickets": "All tickets",
    "sort": "Sort",
    "newest": "Newest",
    "oldest": "Oldest",
    "quickIssueResolution": "Quick issue resolution",
    "version": "FixIT v1.0",
    "welcome": "Welcome",
    "overview": "Overview",
    "statistics": "Statistics",
    "recentActivity": "Recent activity",
    "viewAll": "View all",
    "details": "Details",    "noData": "No data available",
    "recentTickets": "Recently created tickets",
    "openTickets": "Open tickets",
    "inProgressTickets": "In progress",
    "resolvedTickets": "Resolved",
    "back": "Back",
    "closedTickets": "Closed",
    "highPriorityTickets": "High priority",
    "ticketsThisWeek": "Tickets this week",
    "resolutionTime": "Resolution time",
    "ticketsByCategory": "Tickets by category",
    "statusDistribution": "Status distribution",
    "ticketTrends": "Ticket trends",
    "status_open": "Open",
    "status_in_progress": "In progress",
    "status_resolved": "Resolved",
    "status_closed": "Closed",
    "category_hardware": "Hardware",
    "category_software": "Software",
    "category_network": "Network & connectivity",
    "category_email": "Email",
    "category_access": "Access & permissions",
    "category_mobile": "Mobile devices",
    "category_security": "IT security",
    "category_other": "Other",
    "priority": "Priority",
    "priority_toassign": "Priority not assigned",    "priority_high": "High",
    "priority_medium": "Medium",
    "priority_low": "Low",
    "selectPriority": "Select priority",
    "selectPriorityDesc": "Please select the priority for this ticket before assigning it to yourself.",
    "confirm": "Confirm",
    "priority_critical": "Critical",
    "today": "Today",
    "yesterday": "Yesterday",
    "thisWeek": "This week",
    "lastWeek": "Last week",
    "dateCreated": "Date created",
    "dateUpdated": "Date updated",
    "lessThanHour": "Less than 1 hour ago",
    "hoursAgo": "Hours ago",
    "daysAgo": "Days ago",
    "createTicket": "Create ticket",
    "editTicket": "Edit ticket",
    "deleteTicket": "Delete ticket",
    "ticketDetails": "Ticket details",
    "ticketNumber": "Ticket #",
    "description": "Description:",
    "category": "Category",
    "status": "Status",
    "assignedTo": "Assigned to",
    "submittedBy": "Submitted by",
    "created": "Created",
    "updated": "Updated",
    "comments": "Comments",
    "attachedImages": "Attached images",
    "addComment": "Add comment",
    "typeCommentHere": "Type your comment here...",
    "noComments": "No comments yet. Be the first to comment.",
    "commentEmpty": "Comment cannot be empty",
    "mustBeLoggedIn": "You must be logged in to comment",
    "commentAdded": "Comment added successfully",
    "commentAddFailed": "Failed to add comment. Please try again.",
    "commentUpdated": "Comment updated successfully",
    "commentUpdateFailed": "Failed to update comment. Please try again",
    "posting": "Posting...",
    "postComment": "Post comment",
    "resolveTicket": "Close ticket",
    "edit": "Edit",
    "saveChanges": "Save changes",
    "cancel": "Cancel",
    "submit": "Submit",
    "profileSettings": "Profile settings",
    "personalInfo": "Personal information",
    "accountSettings": "Account settings",
    "name": "Name",
    "role": "Role",
    "changePassword": "Change password",
    "currentPassword": "Current password",
    "newPassword": "New password",
    "confirmPassword": "Confirm password",
    "saveProfile": "Save profile",
    "signIn": "Sign in",
    "signUp": "Sign up",
    "forgotPassword": "Forgot password?",
    "resetPassword": "Reset password",
    "enterEmail": "Enter your email",
    "enterPassword": "Enter your password",
    "confirmEmail": "Please confirm your email",
    "rememberMe": "Remember me",
    "error": "Error",
    "success": "Success",
    "warning": "Warning",
    "notification_info": "Information",
    "required": "Required",
    "invalid": "Invalid",
    "passwordMismatch": "Passwords do not match",
    "invalidCredentials": "Invalid email or password",
    "pleaseTryAgain": "Please try again",
    "ticketCreated": "Ticket created successfully",
    "ticketUpdated": "Ticket updated successfully",
    "ticketDeleted": "Ticket deleted successfully",
    "loginSuccess": "Logged in successfully",
    "logoutSuccess": "Logged out successfully",
    "profileUpdated": "Profile updated successfully",
    "assignToMe": "Assign to me",
    "reassignToMe": "Reassign to me",
    "noAdminAssigned": "No administrator assigned",
    "ticketAssigned": "Ticket assigned successfully",
    "preparingTickets": "Preparing tickets",
    "loading": "Loading tickets",
    "sortBy": "Sort by",
    "newestFirst": "Newest first",
    "oldestFirst": "Oldest first",
    "showing": "Showing",
    "ticket": "Ticket",
    "withStatus": "With status",
    "andPriority": "And priority",
    "noTicketsFound": "No tickets found",
    "adjustFilters": "Try adjusting your search or filters, or create a new ticket",
    "all": "All",
    "dateUnknown": "Date unknown",
    "vs": "Vs",
    "days": "Days",
    "errorCreatingTicket": "There was a problem creating your ticket. You can try:",
    "refreshPage": "Refreshing the page and trying again",
    "tryLogout": "Logging out and logging back in",
    "checkConsole": "Checking your browser console for more details",
    "briefSummary": "Brief summary of the issue",
    "keepItShort": "Keep it short and descriptive",
    "selectCategory": "Select category",
    "whatTypeOfIssue": "What type of issue is this?",
    "detailedDescription": "Detailed description of the issue...",
    "provideInformation": "Provide information about the issue you're experiencing",
    "provideRelevantInfo": "Please provide as much relevant information as possible",
    "submitting": "Submitting...",
    "projectStatistics": "Project statistics",
    "totalTickets": "Total tickets",
    "averageResolutionTime": "Average resolution time",
    "unresolvedTickets": "Unresolved tickets",
    "resolvedLastWeek": "Resolved last week",
    "oldestOpenTicket": "Oldest open ticket",
    "categoryDistribution": "Category distribution",
    "darkMode": "Dark mode",
    "lightMode": "Light mode",
    "ticketNotFound": "Ticket not found",
    "ticketNotFoundDesc": "The ticket you're looking for doesn't exist or has been removed.",
    "returnToTickets": "Return to tickets",    "howItWorks": "How it works",    "adminHowItWorks": "Admin Guide",
    "adminHowItWorksIntro": "Complete guide to administrative functionality in the FixIT platform.",
    "adminDashboardStats": "Dashboard and Statistics",
    "adminTicketManagement": "Ticket Management",
    "adminUserManagement": "User Management",
    "adminConfiguration": "Configuration and suggestion management",
    
    "adminDashboardOverview": "Overview",
    "adminDashboardOverviewDesc": "The dashboard offers a complete view of the current system status, showing key metrics and recent activity.",
    "adminRealTimeUpdates": "Real-time Updates",
    "adminRealTimeUpdatesDesc": "Data is automatically updated to provide the most recent information about ticket status.",
    "adminKeyMetrics": "Key Metrics",
    "adminTotalTicketsMetric": "Total open, in progress, and resolved tickets",
    "adminResolutionTimeMetric": "Average resolution time by priority",
    "adminCategoryDistributionMetric": "Ticket distribution by category",
    "adminWeeklyComparisonMetric": "Weekly comparisons of created vs. resolved tickets",
    "adminGoDashboard": "Go to Dashboard",
    
    "adminAdvancedSearch": "Advanced Search",
    "adminAdvancedSearchDesc": "Use filters to quickly find tickets by status, priority, category or user.",
    "adminAssignmentPrioritization": "Assignment and Prioritization",
    "adminAssignmentPrioritizationDesc": "Assign tickets to technicians, set priorities and manage their entire lifecycle.",
    "adminKeyActions": "Key Actions",
    "adminAssignment": "Assignment",
    "adminAssignmentDesc": "You can assign tickets to yourself or reassign them to other technicians as needed.",
    "adminPrioritization": "Prioritization",
    "adminPrioritizationDesc": "Set the appropriate priority (low, medium, high, critical) based on urgency.",
    "adminResolution": "Resolution",
    "adminResolutionDesc": "Mark tickets as resolved when you have fixed the problem.",
    "adminViewTicketList": "View Ticket List",
    
    "adminUserAdmin": "User Administration",
    "adminUserAdminDesc": "Manage all system users, view their data and configure their permissions.",
    "adminRoleAssignment": "Role Assignment",
    "adminRoleAssignmentDesc": "Assign specific roles (user, agent, administrator) to control access level.",
    "adminSystemRoles": "System Roles",
    "roleUser": "User",
    "roleUserDesc": "Can create and view their own tickets, submit suggestions.",
    "roleAgent": "Agent",
    "roleAgentDesc": "Can manage tickets, assign them, change their priority and status.",
    "roleAdmin": "Administrator",
    "roleAdminDesc": "Complete access to all functions, including user management.",
    "adminGoUserManagement": "Go to User Management",
    
    "adminConfigurationAdmin": "Configuration and Administration",
    "adminSystemConfig": "System Configuration",
    "adminSystemConfigDesc": "Access advanced configuration options to customize platform operation.",
    "adminSuggestionManagement": "Suggestion Management",
    "adminSuggestionManagementDesc": "Review and manage all suggestions submitted by users to improve the system.",
    "adminTasks": "Administrative Tasks",
    "adminMonitorSuggestions": "Monitor suggestions",
    "adminMonitorSuggestionsDesc": "submitted by users to identify possible improvements.",
    "adminManageRoles": "Manage roles",
    "adminManageRolesDesc": "assigning appropriate permissions according to each user's responsibilities.",
    "adminReviewStats": "Review statistics",
    "adminReviewStatsDesc": "to identify bottlenecks or areas requiring attention.",
    "adminSetPriorities": "Set priorities",
    "adminSetPrioritiesDesc": "to ensure that the most urgent issues are addressed first.",
    "adminProfileConfig": "Profile Settings",
    "adminManageSuggestions": "Manage Suggestions",
    
    "adminNeedMoreInfo": "Need more information?",
    "adminNeedMoreInfoDesc": "If you need additional assistance or have questions about administrative functions:",
    
    "howItWorksIntro": "Welcome to FixIT. This guide will help you understand how to use our platform effectively.",
    "createTickets": "Create tickets",
    "manageTickets": "Manage tickets",
    "customizeExperience": "Customize",
    "reportingIssues": "Reporting issues",
    "createNewTicket": "Create new ticket",
    "createTicketDesc": "Easily report problems by filling out a simple form with details about your issue.",
    "fillDetails": "Fill in the details",
    "fillDetailsDesc": "Provide information about the issue including category, priority, and a detailed description.",
    "importantTips": "Important tips",
    "tipBeSpecific": "Be specific about what you're experiencing.",
    "tipIncludeScreenshots": "Include screenshots or images when applicable.",
    "tipProvideSteps": "Provide steps to reproduce the issue if possible.",
    "learnMoreTickets": "Learn more about tickets",
    "managingTickets": "Managing your tickets",
    "checkTicketStatus": "Check status",
    "checkStatusDesc": "Monitor the progress of your submitted tickets in real-time.",
    "respondToComments": "Respond to comments",
    "respondCommentsDesc": "Stay engaged by responding to questions or updates from the support team.",
    "statusExplanation": "Understanding ticket status",
    "statusOpenDesc": "Your ticket has been received but not yet assigned.",
    "statusInProgressDesc": "A team member is actively working on your issue.",
    "statusResolvedDesc": "The issue has been fixed and your ticket is closed.",
    "personalizeApp": "Personalizing your experience",
    "profileDesc": "Update your personal information and account settings.",
    "language": "Language",
    "en": "English",
    "es": "Spanish",
    "languageDesc": "Change the application language to your preference.",
    "darkModeDesc": "Switch between light and dark themes for comfortable viewing.",
    "personalSettings": "Personal settings",
    "personalSettingsDesc": "Customize your profile and notification preferences for a better experience.",
    "needMoreHelp": "Need more help?",
    "contactSupport": "If you still have questions, contact our support team:",
    "sendFeedback": "Send feedback",
    "suggestionsAndFeedback": "Suggestions and feedback",
    "suggestImprovements": "Suggest improvements",
    "suggestImprovementsDesc": "Share your ideas on how we can make FixIT better for everyone.",
    "contactTechnical": "Contact technical team",
    "contactTechnicalDesc": "Reach out directly to our technical department with specific concerns.",
    "howToSendSuggestions": "How to send suggestions",
    "suggestionStep1": "Create a new ticket with 'Suggestion' in the title.",
    "suggestionStep2": "Select 'Other' as the category.",
    "suggestionStep3": "Describe your suggestion in detail, explaining the benefits.",
    "suggestionStep4": "Submit your suggestion and our technical team will review it.",
    "viewFeedbackGuidelines": "View feedback guidelines",
    "feedbackDesc": "Submit your feedback directly to our technical department to help us improve.",
    "suggestionDeleted": "Suggestion deleted successfully",
    "helpImproveSystem": "Help us improve our system by sharing your ideas and suggestions",
    "newSuggestion": "New suggestion",
    "mySuggestions": "My suggestions",
    "createNewSuggestion": "Create new suggestion",
    "shareYourIdea": "Share your idea to improve our service",
    "suggestionTitlePlaceholder": "Title of your suggestion",
    "suggestionDescriptionPlaceholder": "Describe your suggestion in more detail...",
    "sending": "Sending...",
    "sendSuggestion": "Send suggestion",
    "suggestionHistory": "History of suggestions you have sent",
    "noSuggestionsYet": "You haven't sent any suggestions yet.",
    "submittedOn": "Submitted on",
    
    // New translations for Call-to-Action
    "readyToCreateTicket": "Ready to create a ticket?",
    "startCreatingTicket": "Get started by creating a new support ticket",
    "createNewTicketNow": "Create a new ticket now",
    "notifications": "Notifications",
    "noNotifications": "No notifications",
    "ticketResolved": "A ticket has been resolved",
    "markAsRead": "Mark as read",
    "deleteNotification": "Delete notification",
    "notificationDeleted": "Notification deleted successfully",
    "confirmResolveTicket": "Confirm ticket resolution",
    "confirmResolveTicketDesc": "Are you sure you want to mark this ticket as resolved?",
    "updating": "Updating..."
  },  es: {
    // Navegación y menú lateral (existentes)
    "statusUpdated": "Estado actualizado correctamente",
    "settings": "Configuración",
    "security": "Seguridad",
    "fullName": "Nombre completo",
    "updateYourInfo": "Actualiza tu información personal",
    "emailCannotBeChanged": "El correo electrónico no se puede cambiar",
    "confirmDeleteTicket": "Borrar ticket",
    "deleteTicketWarning": "Estás seguro de que quieres eliminar este ticket?",
    "createSuggestionNow": "Crear nueva sugerencia",
    "titleIncident": "Título de la incidencia:",
    "descriptionIncident": "Descripción de la incidencia:",
    "noAssignedTickets": "No tienes tickets asignados",
    "noAssignedTicketsDesc": "Aún no tienes tickets asignados a ti",
    "attachImages": "Adjuntar imágenes",
    "uploadImagesDesc": "Sube imágenes relacionadas con tu incidencia. Puedes adjuntar varias imágenes.",
    "clickToUpload": "Haz clic para subir imágenes",
    "recentTickets": "Tickets abiertos recientemente",    
    "back": "Volver",
    "navigation": "Navegación",
    "dashboard": "Panel de estadísticas",
    "tickets": "Tickets",
    "newTicket": "Nuevo ticket",
    "search": "Buscar",    "profile": "Perfil",
    "suggestions": "Sugerencias",
    "adminSuggestions": "Gestionar sugerencias",
    "adminAssignedTickets": "Mis tickets asignados",
    "logout": "Cerrar sesión",
    "language": "Idioma",
    "en": "Inglés",
    "es": "Español",
    "Created": "Creados",
    "Resolved": "Resueltos",
    "quickIssueResolution": "Resolución rápida de incidencias",
    "version": "FixIT v1.0",
    
    // Títulos y subtítulos generales
    "welcome": "Bienvenido",
    "overview": "Resumen",
    "statistics": "Estadísticas",
    "recentActivity": "Actividad reciente",
    "viewAll": "Ver todo",
    "details": "Detalles",
    "noData": "No hay datos disponibles",
    
    // Dashboard
    "openTickets": "Tickets abiertos",
    "inProgressTickets": "En progreso",
    "resolvedTickets": "Resueltos",
    "closedTickets": "Cerrados",
    "highPriorityTickets": "Alta prioridad",
    "ticketsThisWeek": "Tickets creados/resueltos esta semana",
    "resolutionTime": "Media de tiempo de resolución según prioridad",
    "ticketsByCategory": "Tickets por categoría",
    "statusDistribution": "Distribución de tickets según su estado",
    "ticketTrends": "Tendencias de tickets",
    
    // Status y Categorías
    "status_open": "Abierto",
    "status_in_progress": "En progreso",
    "status_resolved": "Resuelto",
    "status_closed": "Cerrado",    "category_hardware": "Hardware",
    "category_software": "Software",
    "category_network": "Redes y conectividad",
    "category_email": "Correo electrónico",
    "category_access": "Acceso y permisos",
    "category_mobile": "Dispositivos móviles",
    "category_security": "Seguridad informática",
    "category_other": "Otros",
      // Prioridades
    "priority": "Prioridad",
    "priority_toassign": "Prioridad no asignada",    "priority_high": "Alta",
    "priority_medium": "Media",
    "priority_low": "Baja",
    "priority_critical": "Crítica",
    "selectPriority": "Seleccionar prioridad",
    "selectPriorityDesc": "Por favor selecciona la prioridad para este ticket antes de asignártelo.",
    "confirm": "Confirmar",
    "priority_info": "Información",
    
    // Tiempo
    "today": "Hoy",
    "yesterday": "Ayer",
    "thisWeek": "Esta semana",
    "lastWeek": "Semana pasada",
    "dateCreated": "Fecha de creación",
    "dateUpdated": "Fecha de actualización",
    "lessThanHour": "Hace menos de 1 hora",
    "hoursAgo": "horas atrás",
    "daysAgo": "días atrás",
    
    // Tickets
    "allTickets": "Todos los tickets",
    "createTicket": "Crear ticket",
    "editTicket": "Editar ticket",
    "deleteTicket": "Eliminar ticket",
    "ticketDetails": "Detalles del ticket",
    "ticketNumber": "Ticket #",
    "title": "Título:",
    "description": "Descripción:",
    "category": "Categoría",
    "status": "Estado",
    "assignedTo": "Asignado a",
    "submittedBy": "Enviado por",
    "created": "Creado",
    "updated": "Actualizado",
    "comments": "Comentarios",
    "attachedImages": "Imágenes adjuntas",
    "addComment": "Añadir comentario",
    "typeCommentHere": "Escribe tu comentario aquí...",
    "noComments": "Aún no hay comentarios. Sé el primero en comentar.",
    
    // Comment actions and messages
    "commentEmpty": "El comentario no puede estar vacío",
    "mustBeLoggedIn": "Debes iniciar sesión para comentar",
    "commentAdded": "Comentario añadido con éxito",
    "commentAddFailed": "Error al añadir el comentario. Por favor, inténtalo de nuevo.",
    "commentUpdated": "Comentario actualizado con éxito",
    "commentUpdateFailed": "Error al actualizar el comentario. Por favor, inténtalo de nuevo.",
    "posting": "Publicando...",
    "postComment": "Publicar comentario",
    "resolveTicket": "Resolver ticket",
    "edit": "Editar",
    "saveChanges": "Guardar cambios",
    "cancel": "Cancelar",
    "submit": "Enviar",
    
    // Perfil
    "profileSettings": "Configuración de perfil",
    "personalInfo": "Información personal",
    "accountSettings": "Configuración de cuenta",
    "name": "Nombre",
    "email": "Correo electrónico",
    "role": "Rol",
    "changePassword": "Cambiar contraseña",
    "currentPassword": "Contraseña actual",
    "newPassword": "Nueva contraseña",
    "confirmPassword": "Confirmar contraseña",
    "saveProfile": "Guardar perfil",
    
    // Autenticación
    "signIn": "Iniciar sesión",
    "signUp": "Registrarse",
    "forgotPassword": "¿Olvidó su contraseña?",
    "resetPassword": "Restablecer contraseña",
    "enterEmail": "Ingrese su correo electrónico",
    "enterPassword": "Ingrese su contraseña",
    "confirmEmail": "Por favor confirme su correo electrónico",
    "rememberMe": "Recordarme",
    
    // Errores y notificaciones
    "error": "Error",
    "success": "Éxito",
    "warning": "Advertencia",
    "notification_info": "Información",
    "required": "Requerido",    "invalid": "Inválido",
    "passwordMismatch": "Las contraseñas no coinciden",
    "invalidCredentials": "Correo electrónico o contraseña inválidos",
    "pleaseTryAgain": "Por favor intente de nuevo",
    "ticketCreated": "Ticket creado con éxito",
    "ticketUpdated": "Ticket actualizado con éxito",
    "ticketDeleted": "Ticket eliminado con éxito",
    "loginSuccess": "Inicio de sesión exitoso",
    "logoutSuccess": "Sesión cerrada con éxito",    
    "profileUpdated": "Perfil actualizado con éxito",
    "assignToMe": "Asignarme",
    "reassignToMe": "Reasignarme",
    "noAdminAssigned": "Sin administrador asignado",
    "ticketAssigned": "Ticket asignado con éxito",
    
    // Listas y filtros
    "preparingTickets": "Cargando tickets...",
    "loading": "Cargando tickets...",
    "sortBy": "Ordenar por",
    "newestFirst": "Más recientes primero",
    "oldestFirst": "Más antiguos primero",
    "showing": "Mostrando",
    "ticket": "ticket",
    "withStatus": "con estado",
    "andPriority": "y prioridad",
    "noTicketsFound": "No se encontraron tickets.",
    "adjustFilters": "Intente ajustar su búsqueda o filtros, o cree un nuevo ticket",
    "all": "Todos",
    "dateUnknown": "Fecha desconocida",
    "vs": "vs",
    "days": "días",
    
    // NewTicket
    "errorCreatingTicket": "Hubo un problema al crear su ticket. Puede intentar:",
    "refreshPage": "Actualizar la página e intentar nuevamente",
    "tryLogout": "Cerrar sesión y volver a iniciar sesión",
    "checkConsole": "Revisar la consola del navegador para más detalles",
    "briefSummary": "Breve resumen del problema",
    "keepItShort": "Manténgalo corto y descriptivo",
    "selectCategory": "Seleccionar categoría",
    "whatTypeOfIssue": "¿Qué tipo de problema es este?",
    "detailedDescription": "Descripción detallada del problema...",
    "provideInformation": "Proporcione información sobre el problema que está experimentando",
    "provideRelevantInfo": "Por favor proporcione toda la información relevante posible",
    "submitting": "Enviando...",    // ProjectStats keys
    "projectStatistics": "Estadísticas del proyecto",
    "totalTickets": "Total de tickets",
    "averageResolutionTime": "Tiempo medio de resolución",
    "unresolvedTickets": "Tickets sin resolver",
    "resolvedLastWeek": "Resueltos la última semana",
    "oldestOpenTicket": "Ticket abierto más antiguo",
    "categoryDistribution": "Distribución por categoría",
    // Theme Toggle
    "darkMode": "Modo oscuro",
    "lightMode": "Modo claro",
    // For categories, already present: category_technical, category_billing, category_account, category_other

    // Error messages
    "ticketNotFound": "Ticket no encontrado",
    "ticketNotFoundDesc": "El ticket que buscas no existe o ha sido eliminado.",
    "returnToTickets": "Volver a tickets",
      // How It Works Page
    "howItWorks": "Bienvenido a FixIT!",
    "adminHowItWorks": "Guía de administrador",
    "adminHowItWorksIntro": "Guía completa de funcionalidades administrativas en la plataforma FixIT.",
    "adminDashboardStats": "Dashboard y Estadísticas",
    "adminTicketManagement": "Gestión de Tickets",
    "adminUserManagement": "Gestión de Usuarios",
    "adminConfiguration": "Configuración y gestión de sugerencias",
    
    "adminDashboardOverview": "Visión General",
    "adminDashboardOverviewDesc": "El dashboard ofrece una visión completa del estado actual del sistema, mostrando métricas clave y actividad reciente.",
    "adminRealTimeUpdates": "Actualización en Tiempo Real",
    "adminRealTimeUpdatesDesc": "Los datos se actualizan automáticamente para proporcionar la información más reciente sobre el estado de los tickets.",
    "adminKeyMetrics": "Métricas Principales",
    "adminTotalTicketsMetric": "Total de tickets abiertos, en progreso y resueltos",
    "adminResolutionTimeMetric": "Tiempo medio de resolución por prioridad",
    "adminCategoryDistributionMetric": "Distribución de tickets por categoría",
    "adminWeeklyComparisonMetric": "Comparativas semanales de tickets creados vs. resueltos",
    "adminGoDashboard": "Ir al Dashboard",
    
    "adminAdvancedSearch": "Búsqueda Avanzada",
    "adminAdvancedSearchDesc": "Utiliza los filtros para encontrar rápidamente tickets por estado o prioridad",
    "adminAssignmentPrioritization": "Asignación y Priorización",
    "adminAssignmentPrioritizationDesc": "Asigna tickets, establece prioridades y gestiona su ciclo de vida completo.",
    "adminKeyActions": "Acciones Principales",
    "adminAssignment": "Asignación",
    "adminAssignmentDesc": "Puedes asignarte tickets.",
    "adminPrioritization": "Priorización",
    "adminPrioritizationDesc": "Establece la prioridad adecuada (baja, media, alta, crítica) según la urgencia.",
    "adminResolution": "Resolución",
    "adminResolutionDesc": "Marca los tickets como resueltos cuando hayas solucionado el problema.",
    "adminViewTicketList": "Ver Listado de Tickets",
    
    "adminUserAdmin": "Administración de Usuarios",
    "adminUserAdminDesc": "Gestiona todos los usuarios del sistema, visualiza sus datos y configura sus permisos.",
    "adminRoleAssignment": "Asignación de Roles",
    "adminRoleAssignmentDesc": "Asigna roles específicos (usuario, agente, administrador) para controlar el nivel de acceso.",
    "adminSystemRoles": "Roles del Sistema",
    "roleUser": "Usuario",
    "roleUserDesc": "Puede crear y ver sus propios tickets, enviar sugerencias.",
    "roleAgent": "Agente",
    "roleAgentDesc": "Puede gestionar tickets, asignarlos, cambiar su prioridad y estado.",
    "roleAdmin": "Administrador",
    "roleAdminDesc": "Acceso completo a todas las funciones, incluyendo gestión de usuarios.",
    "adminGoUserManagement": "Ir a Gestión de Usuarios",
    
    "adminConfigurationAdmin": "Configuración y Administración",
    "adminSystemConfig": "Configuración del Sistema",
    "adminSystemConfigDesc": "Accede a opciones avanzadas de configuración para personalizar el funcionamiento de la plataforma.",
    "adminSuggestionManagement": "Gestión de Sugerencias",
    "adminSuggestionManagementDesc": "Revisa y gestiona todas las sugerencias enviadas por los usuarios para mejorar el sistema.",
    "adminTasks": "Tareas Administrativas",
    "adminMonitorSuggestions": "Supervisa las sugerencias",
    "adminMonitorSuggestionsDesc": "enviadas por los usuarios para identificar posibles mejoras.",
    "adminManageRoles": "Gestiona los roles",
    "adminManageRolesDesc": "asignando los permisos adecuados según las responsabilidades de cada usuario.",
    "adminReviewStats": "Revisa las estadísticas",
    "adminReviewStatsDesc": "para identificar cuellos de botella o áreas que requieren atención.",
    "adminSetPriorities": "Establece prioridades",
    "adminSetPrioritiesDesc": "para garantizar que los problemas más urgentes sean atendidos primero.",
    "adminProfileConfig": "Configuración de Perfil",
    "adminManageSuggestions": "Gestionar Sugerencias",
    
    "adminNeedMoreInfo": "¿Necesitas más información?",
    "adminNeedMoreInfoDesc": "Si necesitas asistencia adicional o tienes preguntas sobre las funciones administrativas:",
    
    "howItWorksIntro": "Esta guía te ayudará a entender cómo usar nuestra plataforma de manera efectiva. Recuerda que si tienes alguna duda, siempre puedes contactar a nuestro equipo de soporte.",
    "createTickets": "Crear tickets",
    "manageTickets": "Gestionar tickets",
    "customizeExperience": "Personalizar",
    "reportingIssues": "Reportar incidencias",
    "createNewTicket": "Crear nuevo ticket",
    "createTicketDesc": "Reporta problemas fácilmente completando un formulario simple con detalles sobre tu incidencia.",
    "fillDetails": "Completa los detalles",
    "fillDetailsDesc": "Proporciona información sobre el problema incluyendo categoría, prioridad y una descripción detallada.",
    "importantTips": "Consejos importantes",
    "tipBeSpecific": "Sé específico sobre lo que estás experimentando.",
    "tipIncludeScreenshots": "Incluye capturas de pantalla o imágenes cuando sea posible.",
    "tipProvideSteps": "Proporciona los pasos para reproducir el problema si es posible.",
    "learnMoreTickets": "Aprende más sobre tickets",
    "managingTickets": "Gestiona tus tickets",
    "checkTicketStatus": "Consultar estado",
    "checkStatusDesc": "Supervisa el progreso de tus tickets enviados en tiempo real.",
    "respondToComments": "Responder a comentarios",
    "respondCommentsDesc": "Mantente involucrado respondiendo a preguntas o actualizaciones del equipo de soporte.",
    "statusExplanation": "Entendiendo los estados del ticket",
    "statusOpenDesc": "Tu ticket ha sido recibido pero aún no ha sido asignado.",
    "statusInProgressDesc": "Un miembro del equipo está trabajando activamente en tu problema.",
    "statusResolvedDesc": "El problema ha sido resuelto y tu ticket está cerrado.",
    "personalizeApp": "Personalizando tu experiencia",
    "profileDesc": "Actualiza tu información personal y la configuración de la cuenta.",
    "languageDesc": "Cambia el idioma de la aplicación según tu preferencia.",
    "darkModeDesc": "Alterna entre temas claros y oscuros para una visualización más cómoda.",
    "personalSettings": "Configuración personal",
    "personalSettingsDesc": "Personaliza tu perfil y preferencias de notificación para una mejor experiencia.",
    "needMoreHelp": "¿Necesitas más ayuda?",
    "contactSupport": "Si aún tienes preguntas, contacta a nuestro equipo de soporte:",
    
    // New Suggestions Tab
    "readyToCreateSuggestion": "¿Listo para sugerir?",
    "startCreatingSuggestion": "Si consideras que FixIT puede mejorar, ¡comienza creando una nueva sugerencia!",
    "sendFeedback": "Enviar sugerencias",
    "suggestionsAndFeedback": "Sugerencias y comentarios",
    "suggestImprovements": "Sugerir mejoras",
    "suggestImprovementsDesc": "Comparte tus ideas sobre cómo podemos mejorar FixIT para todos.",
    "contactTechnical": "Contactar al equipo técnico",
    "contactTechnicalDesc": "Comunícate directamente con nuestro departamento técnico para consultas específicas.",
    "howToSendSuggestions": "Cómo enviar sugerencias",
    "suggestionStep1": "Accede al apartado de sugerencias.",
    "suggestionStep2": "Elige un título para tu sugerencia.",
    "suggestionStep3": "Describe tu sugerencia en detalle, explicando los beneficios.",
    "suggestionStep4": "Envía tu sugerencia y nuestro equipo técnico la revisará.",
    "viewFeedbackGuidelines": "Ver pautas para sugerencias",
    "feedbackDesc": "Envía tus comentarios directamente a nuestro departamento técnico para ayudarnos a mejorar.",
    "suggestionDeleted": "Sugerencia eliminada con éxito",
    "helpImproveSystem": "Ayúdanos a mejorar nuestro sistema compartiendo tus ideas y sugerencias.",
    "newSuggestion": "Nueva sugerencia",
    "mySuggestions": "Mis sugerencias",
    "createNewSuggestion": "Crear nueva sugerencia",
    "shareYourIdea": "Comparte tu idea para mejorar nuestro servicio",
    "suggestionTitlePlaceholder": "Título de tu sugerencia",
    "suggestionDescriptionPlaceholder": "Describe tu sugerencia con más detalle...",
    "sending": "Enviando...",
    "sendSuggestion": "Enviar sugerencia",
    "suggestionHistory": "Historial de sugerencias que has enviado",
    "noSuggestionsYet": "Aún no has enviado ninguna sugerencia.",
    "submittedOn": "Enviado el",
    
    // Nuevas traducciones para Call-to-Action
    "readyToCreateTicket": "¿Listo para crear un ticket?",
    "startCreatingTicket": "Comienza creando un nuevo ticket de soporte",
    "createNewTicketNow": "Crear un nuevo ticket ahora",
    "notifications": "Notificaciones",
    "noNotifications": "No hay notificaciones",
    "ticketResolved": "Un ticket ha sido resuelto",
    "markAsRead": "Marcar como leída",
    "deleteNotification": "Eliminar notificación",
    "notificationDeleted": "Notificación eliminada con éxito",
    "confirmResolveTicket": "Confirmar resolución de ticket",
    "confirmResolveTicketDesc": "¿Estás seguro de que quieres marcar este ticket como resuelto? Esta acción no se puede deshacer.",
    "updating": "Actualizando..."
  }
};

export function useLanguage() {
  // Detectar el idioma guardado o usar el del navegador
  const getInitialLanguage = () => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es')) {
      return savedLanguage;
    }
    // Si no hay idioma guardado, intentar detectar el del navegador
    const browserLang = navigator.language.split('-')[0];
    return browserLang === 'es' ? 'es' : 'en'; // Valores por defecto
  };

  const [currentLanguage, setCurrentLanguage] = useState(getInitialLanguage());

  // Función para cambiar el idioma
  const changeLanguage = (lng: string) => {
    if (lng === 'en' || lng === 'es') {
      setCurrentLanguage(lng);
      localStorage.setItem('language', lng);
      window.location.reload(); // Recarga la página al cambiar el idioma
    }
  };

  // Función para traducir un texto
  const t = (key: string) => {
    return translations[currentLanguage as keyof typeof translations]?.[key] || key;
  };

  // Efecto para guardar el idioma cuando cambia
  useEffect(() => {
    localStorage.setItem('language', currentLanguage);
  }, [currentLanguage]);

  return {
    t,
    changeLanguage,
    currentLanguage
  };
}